config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_foot.html.erb
<footer class="footer-distributed">
  
          <div class="footer-left"> 

                <h3>Company<span>logo</span></h3> 
                
                <p class="footer-links">
                      <a href="#">Home</a> 
                      ·
                      <a href="#">Blog</a>
                      ·
                      <a href="#">Pricing</a> 
                      ·
                      <a href="#">About</a> 
                      ·
                      <a href="#">Faq</a>
                      ·
                      <a href="#">Contact</a>
                </p>
                
                <p class="footer-company-name">Company Name &copy; 2016</p> 

                <div class="footer-icons">
  
                        <a href="#"><i class="fa fa-facebook"></i></a> 
                        <a href="#"><i class="fa fa-twitter"></i></a> 
                        <a href="#"><i class="fa fa-linkedin"></i></a> 
                        <a href="#"><i class="fa fa-github"></i></a>

                ￼</div>

          </div>
          
          <div class="footer-right"> 
          
                  <p>Contact Us</p>
                  
                  <form action="#" method="post">
                    
                          <input type="text" name="email" placeholder="Email" />
                          <textarea name="message" placeholder="Message"></textarea> 
                          <button>Send</button>
                          
                  </form> 
                  
          </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RetroBlast's Articles", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><a href="#">Link</a></li>
        
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact Us" , pages_contact_path %></li>
        <li><%= link_to "About Us" , pages_about_path %></li>
        <li><%= link_to "Sign Up" , new_user_registration_path %></li>
        <li><%= link_to "Sign In" , new_user_session_path %></li>
        <li><%= link_to "Sign Out" , destroy_user_session_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RetroBlast Articles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
<%= bootstrap_flash %>
<div class='container'>
  <%= yield %>
</div>
<%= render 'layouts/foot' %>
</body>
</html>

app/views/pages/about.html.erb
              <!--About Page--> 
<div class="row">
  <div class="col-lg-12 text-center"> 
    <h1>About Us</h1>
    <p class="lead">Test Text</p> 
    <ul class="list-unstyled">
        <li>List Item</li>
        <li>List Item 2</li>   
    </ul>
  </div> 
</div>

app/views/pages/contact.html.erb
<!--Contact Page--> 
<div class="row">
 <div class="col-lg-12 text-center"> 
   <h1>Contact Us</h1>
   <p class="lead">Test Text</p> 
   <ul class="list-unstyled">
     <li>List Item</li>
     <li>List Item 2</li> 
    </ul>
  </div> 
</div>

app/views/pages/index.html.erb
<!--Index Page-->
      <div class="row">
  <!-- Blog Post Content Column --> 
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1>Blog Post Title</h1>

    ￼<!-- Author -->
    <p class="lead">
      by <a href="#">Start Bootstrap</a> 
      </p>
      
      <hr>
      
      <!-- Date/Time -->
      <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
      
      <hr>
      <!-- Preview Image -->
      <img class="img-responsive" src="http://placehold.it/900x300" alt="">
      
      <hr>
      
      <!-- Post Content -->
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

       <hr>
       
       <!-- Blog Comments -->
       <!-- Comments Form --> 
       <div class="well">
          <h4>Leave a Comment:</h4> 
          <form role="form">
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button> 
          </form>
        </div> 
        
        <hr>

￼￼
        ￼<!-- Posted Comments -->
        
        <!-- Comment --> 
        <div class="media">
          <a class="pull-left" href="#">
             <img class="media-object" src="http://placehold.it/64x64" alt="">
          </a>
          <div class="media-body">
            <h4 class="media-heading">Start Bootstrap 
              <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div> 
          </div>
          
          <!-- Comment --> 
          <div class="media">
             <a class="pull-left" href="#">
               <img class="media-object" src="http://placehold.it/64x64" alt="">
             </a>
             <div class="media-body">
                <h4 class="media-heading">Start Bootstrap 
                  <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                <!-- Nested Comment --> 
                <div class="media">
                  <a class="pull-left" href="#">
                   <img class="media-object" src="http://placehold.it/64x64" alt="">
                  </a>
                  <div class="media-body">
                    <h4 class="media-heading">Nested Start Bootstrap 
                      <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div> 
                  </div>
                  <!-- End Nested Comment --> 
              </div>
            </div> 
            
        </div>
        <!-- Blog Sidebar Widgets Column --> 
        <div class="col-md-4">
          
        <!-- Blog Search Well --> 
        <div class="well">
          <h4>Blog Search</h4> 
          <div class="input-group">
            <input type="text" class="form-control"> 
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            </span> 
          </div>
          <!-- /.input-group --> 
        </div>
        
        <!-- Blog Categories Well --> 
        
        <div class="well">
          <h4>Blog Categories</h4> 
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled">
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
              </ul> 
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled">
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
                <li><a href="#">Category Name</a> 
                </li>
              </ul> 
            </div>
          </div>
          <!-- /.row --> 
        </div>
        
       <!-- Side Widget Well -->
       
       <div class="well">
         <h4>Side Widget Well</h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p> 
       </div>
       
    </div>
    
</div>
<!-- /.row -->

<hr>